### ISSUE TITLE
Admonition can not rendered in result window

### ISSUE THREAD

**Issue by rushfly** [SeptemberHX/joplin-plugin-enhancement#10]
![image](https://user-images.githubusercontent.com/1964855/188323096-fdbd7208-41b1-4d31-85c2-0b4c6ec4aea7.png)

May I need anything else?

**Comment by SeptemberHX** [comment]
Hello, it seems the documentation is somewhat unclear, and I will update the document as soon as possible.

You still need `Admonition markdown extension` plugin installed to render admonitions in the preview window & PDF exports. This plugin only renders admonitions in the markdown editor.

**Comment by Zeg31** [comment]
Simply add the description "It NEEDS joplin-plugin-admonition plugin installed". (As done for another option.)
