### ISSUE TITLE
[bug] Markdown-Links are not visible in editor

### ISSUE THREAD

**Issue by monnypython** [SeptemberHX/joplin-plugin-enhancement#11]
Hi, thanks for this good plugin.

However, I have a problem displaying markdown links. As you can see in the video, after pasting the link of another note, only an empty field appears in the editor. Everything is correct in the render window. If you put a hyphen in front of the link, everything seems to work normally.

https://user-images.githubusercontent.com/42573701/188868166-443a2d6e-d93c-49bc-a8d0-366ef8d403a6.mp4

**Comment by monnypython** [comment]
Thanks.
I tested the update. Looks pretty cool. For my taste, the block display could be a bit smaller overall (lower area in the image) and the URL could certainly be hidden, right?

![image](https://user-images.githubusercontent.com/42573701/189069380-13bfc714-3177-4001-863c-b1d0c3b33286.png)

**Comment by SeptemberHX** [comment]
This bug should be fixed in v0.4.2.
