### ISSUE TITLE
[bug]SequenceDiagram in mermaid shows different content than the code

### ISSUE THREAD

**Issue by aojiru-ts** [SeptemberHX/joplin-plugin-enhancement#12]
Thank you for the great plugin.
I noticed that the following operation on mermaid's SequenceDiagram displays a graph that is different from the content of the code.

## Operation:
Write several different SequenceDIagrams and display the graphs.

## Expected:
A graph identical to the contents of the code is displayed.

## Current behavior:
A graph different from the contents of the code is displayed.

https://user-images.githubusercontent.com/45072106/189504419-47831ff0-3883-4dad-b218-1c387c0b4378.mp4

**Comment by SeptemberHX** [comment]
I can confirm this bug.

It's wired. It seems `mermaid.js` keeps the context for the `sequenceDiagram` rendered before, even they are not in the same `mermaid` code block, just like concat them into one.

**Comment by SeptemberHX** [comment]
I think I fix it by downgrading `mermaid.js` to v8.14.0. You can try the attached new build plugin:

[com.septemberhx.Joplin.Enhancement.jpl.zip](https://github.com/SeptemberHX/joplin-plugin-enhancement/files/9541767/com.septemberhx.Joplin.Enhancement.jpl.zip)

**Comment by aojiru-ts** [comment]
I have tried using the build plugin attached and the graph seems to be rendering correctly.

![image](https://user-images.githubusercontent.com/45072106/189518674-de1f296f-d6c4-4dfc-9c83-c97f0b47239b.png)

![image](https://user-images.githubusercontent.com/45072106/189518391-1b4df5cb-55c0-4961-80c7-053d727a5189.png)

**Comment by aojiru-ts** [comment]
It appears that this issue is a bug in v9.1.4 of `mermaid.js`.
https://github.com/mermaid-js/mermaid/issues/3305

**Comment by SeptemberHX** [comment]
This bug should be solved in v1.1.2.
