### ISSUE TITLE
disable bullet list rendering

### ISSUE THREAD

**Issue by tino926** [SeptemberHX/joplin-plugin-enhancement#14]
Is there a way to disable the bullet list rendering?
Compared with the original "-" symbol,  I am really uncomfortable with the dot symbol ...

**Comment by SeptemberHX** [comment]
Currently there is no option to disable it. I will add it in the future release.

**Comment by pravsripad** [comment]
I have the same request - to be able to see "-" and not the bullet list rendering. Currently I see the option "Enable bullet list rendering in markdown editor" , is it supposed to work?

**Comment by pravsripad** [comment]
Thank you very much, I'll give it a try.

**Comment by pravsripad** [comment]
Works well for me. Thanks for the quick fix.
