### ISSUE TITLE
[feature] Open with...Image

### ISSUE THREAD

**Issue by monnypython** [SeptemberHX/joplin-plugin-enhancement#15]
I work a lot with screenshots which I like to open in an external editor. It would be very helpful here if the functionality from the render view "Right-Click--> Open...." was also possible in the editor.

Since I installed the "enhancement plugin" I work almost exclusively in the editor. I just have to switch to render view to open images :|

**Comment by SeptemberHX** [comment]
Try cmd/ctrl + left click on the image! It should work or there exist bugs. The plugin is designed with this feature.

**Comment by monnypython** [comment]
Unfortunately it does not work. I get a cursor when I hover over the image but no context menu appears.

I work with the following system:
WIN10
Joplin 2.8.8
joplin-plugin-enhancement v1.1.1

![joplin-OpenImage](https://user-images.githubusercontent.com/42573701/191674013-47fb9e72-0ed9-4fe5-8709-b9e0b69486d5.gif)

**Comment by SeptemberHX** [comment]
What about `Win + left click`?

**Comment by monnypython** [comment]
YES! That`s it! 
Thank you.

**Comment by SeptemberHX** [comment]
It is already in the `link/image/footnote renderer in the editor` section of the document.

I probably need to reorganize the documentation for clarity 😄
