### ISSUE TITLE
Option to disable all markdown editor enhancements

### ISSUE THREAD

**Issue by pravsripad** [SeptemberHX/joplin-plugin-enhancement#21]
Would it be possible to create an option to disable all enhancements to the markdown editor in one go? 

I currently only use the image resize option and find the markdown editor changes distracting. I also notice a slight lag when when rendering. This option might help users like myself. 

Thank you.

**Comment by SeptemberHX** [comment]
Sorry, there is no plan to add such an option to disable them. You can manually disable all the features separately instead.
