### ISSUE TITLE
Dark mode for Header tag render in markdown editor

### ISSUE THREAD

**Issue by advait404** [SeptemberHX/joplin-plugin-enhancement#23]
The Header tag render does not work well when using Joplin in dark mode. Mostly, the text color inside it that shows the 'tick mark' and '#' should be changed.

![image](https://user-images.githubusercontent.com/83760070/199166208-cf4e70dd-74b8-4e1b-8493-04418c38cabf.png)

**Comment by SeptemberHX** [comment]
It was already fixed but not published yet. You can try it with the attachment.

[com.septemberhx.Joplin.Enhancement.jpl.zip](https://github.com/SeptemberHX/joplin-plugin-enhancement/files/9907407/com.septemberhx.Joplin.Enhancement.jpl.zip)
