### ISSUE TITLE
Joplin icon not rendering before links in markdown

### ISSUE THREAD

**Issue by ludibelli** [SeptemberHX/joplin-plugin-enhancement#24]
I'm trying to find the cause and fix it by myself but, til now, was unsuccessful.

![image](https://user-images.githubusercontent.com/7178862/200177201-6eaa58dc-6a03-4a16-aaa7-b7271d283eb2.png)
![image](https://user-images.githubusercontent.com/7178862/200177217-3d96372a-b2c2-4a9c-8a7e-be0905369ab4.png)

![image](https://user-images.githubusercontent.com/7178862/200177252-29f63056-755b-40d0-b138-1efbc7bd2875.png)

### UPDATE:

Found the issue! 
The problem is the `background-color: var(-g--linkColor);`  property. It was setting it to a transparent color so I changed
it to `background-color: var(--joplin-url-color);` that makes it match the Joplin theme (i guess?).

![image](https://user-images.githubusercontent.com/7178862/200187350-016a427a-0591-41e7-9c82-13e04780e9ec.png)

**Comment by SeptemberHX** [comment]
Thanks for the report! And yes, it should be `var(--joplin-url-color);` instead of `var(-g--linkColor)`
