### ISSUE TITLE
[[TOC]] preview feature request

### ISSUE THREAD

**Issue by ahxxm** [SeptemberHX/joplin-plugin-enhancement#26]
My motivation of using this plugin is to get rid of right panel, being able to preview and jump from generated TOC in live preview would make the editing experience more friendly!

A bare minimum snippet 
```markdown
[[TOC]]

# Some H1
## Some H2
```

![image](https://user-images.githubusercontent.com/1286225/202832098-2a22b078-161b-4d3b-be1f-39c4414eb242.png)

**Comment by SeptemberHX** [comment]
Though it is possible to implement this, considering the cost required to implement this feature, I prefer to display the table of contents via the sidebar plugin. The sidebar style is much more practical with a very long note.

You can try the plugin [joplin-outline](https://github.com/cqroot/joplin-outline) and [joplin-plugin-bundle](https://github.com/SeptemberHX/joplin-plugin-bundle).

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/18042424/213125826-5bd2881a-4b2a-4ba0-9030-8a68c3b08c08.png">

**Comment by ahxxm** [comment]
Thanks! the outline plugin is exactly what I want, hope these 2 plugins work together happily
