### ISSUE TITLE
Image icon display fix

### ISSUE THREAD

**Issue by Ratinod** [SeptemberHX/joplin-plugin-enhancement#29]
At the moment there is a problem with the display of the icon images.
(7,8 - ignore it)
3,5,6 - great
1,2,4 - not replaced by icon
9,10 - bad
11 - show name
![linebug](https://user-images.githubusercontent.com/12137233/218279588-20de146c-e69a-4892-860d-56e781360f03.png)

Is there any way to hotfix this with userstyle.css or userchrome.css? At least 9 and10.

**Comment by SeptemberHX** [comment]
It should be fixed now. You can try it with the attached plugin file.

[com.septemberhx.Joplin.Enhancement.jpl.zip](https://github.com/SeptemberHX/joplin-plugin-enhancement/files/10717792/com.septemberhx.Joplin.Enhancement.jpl.zip)

**Comment by Ratinod** [comment]
> It should be fixed now. You can try it with the attached plugin file.
> 
> [com.septemberhx.Joplin.Enhancement.jpl.zip](https://github.com/SeptemberHX/joplin-plugin-enhancement/files/10717792/com.septemberhx.Joplin.Enhancement.jpl.zip)

![fixedimage](https://user-images.githubusercontent.com/12137233/218352656-a278a1fc-a176-4c9e-9036-1c7359151222.png)
Now everything looks great. A great plugin just got better :) .
Thanks for the work you've done!
<sub><sub><sup>How much I envy those who understand css...</sup></sub></sub>
