### ISSUE TITLE
bullet lists always rendering in markdown editor, regardless of settings

### ISSUE THREAD

**Issue by ecelien** [SeptemberHX/joplin-plugin-enhancement#33]
The **"Enable bullet list rendering in markdown editor"** option in the plugin settings does not appear to function properly, even after restarting Joplin. I am certain that I am doing a full quit of Joplin and have no other plugins installed.

### With plugin disabled:
Disabling the plugin entirely produced the desired, default, rendering of markdown bullet lists.

![image](https://user-images.githubusercontent.com/83480308/222908993-d59da77a-e2ac-4611-85cb-f619b4c9e783.png)

### With rendering disabled:
With the plugin enabled, bullet lists were always rendered as bullets in the markdown editor, regardless of whether "**Enable bullet list rendering in markdown editor (Restart required)**" was enabled or disabled. 

![image](https://user-images.githubusercontent.com/83480308/222908460-68b14e53-1f4b-44d5-b1e8-331ae72ed44d.png)

This was tested after a full Joplin restart. This result did not change when every other option was disabled as well.

**Comment by SeptemberHX** [comment]
It should be fixed now. You can test with the attached version:

[com.septemberhx.Joplin.Enhancement.jpl.zip](https://github.com/SeptemberHX/joplin-plugin-enhancement/files/10890624/com.septemberhx.Joplin.Enhancement.jpl.zip)

**Comment by ecelien** [comment]
Thank you! This seems to work perfectly now.
