### ISSUE TITLE
请问示例图片中的css和安装的插件都有哪些

### ISSUE THREAD

**Issue by bricle** [SeptemberHX/joplin-plugin-enhancement#34]
![](https://iili.io/HNQd4Jj.png)
麻烦问一下图中圈出的按钮是哪个插件谢谢大佬

**Comment by SeptemberHX** [comment]
* 主题插件：MacOS theme
* 图例的插件：joplin-plugin-bundle
* Admonition PDF 渲染：Admonition markdown extension

主要就这几个
