### ISSUE TITLE
"Automatically correct list numbering when editing" messes up code blocks and raw list of domain names

### ISSUE THREAD

**Issue by oleole39** [SeptemberHX/joplin-plugin-enhancement#35]
Hello,

Using Joplin 2.9.17 AppImage for Linux with Enhancement plugin v.1.2.0, I find that checking the option _Automatically correct list numbering when editing lists_ in Joplin Enhancement settings brings the following unwanted behaviour while editing below snippet:  
````
```js
const items = ["world", "you"];
items.forEach(function (item) {
    console.log("hello " + item)
  });
```
test.com
https://test.com
````

The plugin option will force saving the following:
````
```js
const items = ["world", "you"];
a.forEach(function (item) {
    a.log("hello " + item)
  });
```
a.com
https://test.com
````

I assume this is due to the regex matching any continuous word pattern before the dot. 
- A **quick fix** could be matching exclusively one letter (instead of several) before a dot. That would break use cases such as roman numerals support for instance (i., ii., iii., ...), but autocorrection for this format is not implemented so far and I can't think of other use case which would require to have letter before a dot in a list (actually the script uses multiple letters over 26 list items, like `[...], x. , y., z., aa., ab., ac., [...]`, but I don't know how common it is to see that).
   - Changing [this regex pattern](https://github.com/SeptemberHX/joplin-plugin-enhancement/blob/4b79933dee455f2a3a052157151ccc15669c357e/src/driver/codemirror/listNumber/index.ts#L3) from `/^\s*[\d|a-z]+\./` to `/^\s*[\d|a-z]\./`.
   - Maybe also changing [this other regex pattern](https://github.com/SeptemberHX/joplin-plugin-enhancement/blob/master/src/driver/codemirror/listNumber/index.ts#L101) from `/[a-z]+\./` to `/[a-z]\./` 
- An **additional fix** could also ignore anything in inline and multilines code blocks. 
  - With the help of [that thread](https://stackoverflow.com/questions/64285562/parse-urls-using-regex-ignoring-code-blocks-and-code-snippets-in-markdown), I found out this regex could work: ``(?<!`)(`(?:`+)?)(?:(?!\1).)*?\1|(^\s*[\d|a-z]\.)``. It can be [tested here](https://regex101.com/r/LquyoO/3) and requires: 
    - to enable single line match option in regex settings.
    - to assign the regex result to a variable from which will be retrieved only the results of the second capture group.
  - However I went a bit fast in my research, as I noted afterwards that the script seems actually to be checking the text with a scope limited to each selected line (where the cursor is positioned) and I have no more time to think of a correct implementation to ignore codeblocks right now.
  
Note that I tested the regex but not the proposed fixes themselves in the plugin.

**Comment by SeptemberHX** [comment]
Thank you for your feedback and the suggestions for the fix !

Since the token type of the lines in codeblocks are set to `jn-monospace` in CodeMirror, we can ignore all the lines with `jn-monospace` token type:

```typescript
const token = cm.getTokenTypeAt({line: lineN, ch: 0});
if (token && token.includes('jn-monospace')) {
    continue;
}
```

**Comment by oleole39** [comment]
Thanks for the quick review.
That's a short and efficient fix - successfully tested as far as code blocks are concerned! 

Now the issue is still here for a "raw list" (without bullets) of domain names for instance
```
test.com
anothertest.org  
```
will get transformed as 
```
a.com
b.org
```
For this, my quickfix suggestion above should work, if you are willing to accept the associated constraint (only single letter before dot. Untested though, not sure what the script would do after z. is reached!

**Comment by SeptemberHX** [comment]
It should be fixed now. I just realized that we only need to deal with something like `a. xxx` instead of `a.xxx`.

[com.septemberhx.Joplin.Enhancement.jpl.zip](https://github.com/SeptemberHX/joplin-plugin-enhancement/files/11296179/com.septemberhx.Joplin.Enhancement.jpl.zip)
