### ISSUE TITLE
Something is affecting the code block content accidentally.

### ISSUE THREAD

**Issue by Sinacs** [SeptemberHX/joplin-plugin-enhancement#37]
OS: Win11Pro
Joplin: v2.10.16
Enhancement: v1.2.0

## Recreating the problem

1. Open Joplin
2. Open a new note
3. Create a code block as below:
(I use blockquote to show the code because the code block doesn't allow nesting another code block)
> \```js
>
> \```

4. Typing `document.getElementById()` within the code block:

> \```js
> document.getElementById()
> \```

## Describe the problem

When you follow the above steps to recreate the problem, the problem will be triggered when you are typing the `.` character. Normally, we expect to see the result as `document.` but Enhancement changed it to `a.`.

**Comment by SeptemberHX** [comment]
It looks like the same issue as https://github.com/SeptemberHX/joplin-plugin-enhancement/issues/35

You can test the new build plugin: https://github.com/SeptemberHX/joplin-plugin-enhancement/issues/35#issuecomment-1517849237

If it works fine, I will push it to the plugin repo :)

**Comment by Sinacs** [comment]
I've just tested it, and it seems to work well. Thank you!
