### ISSUE TITLE
All kinds of formatting inside tables automatically get removed

### ISSUE THREAD

**Issue by Pyroseza** [SeptemberHX/joplin-plugin-enhancement#42]
When I try to use the following formatting inside of tables it will disappear either right away or when I click away from the cell and then back in it:
- lists, both ordered and unordered
- links
- images
- bold, italic, underline when using the control shortcuts or clicking the editor buttons, these have to be typed out for them to stay
- line breaks `<br>`

The problem is definitely with this Enhancement plugin as everything works fine when I disable it.

**Comment by SeptemberHX** [comment]
The table rendering feature was directly taken from the Zettlr code repository. It does indeed have some bugs and does not integrate well with other rendering functionalities.

Unfortunately, I do not have the ability to fix these issues. I would recommend disabling this feature.

**Comment by Pyroseza** [comment]
Can you please refer me to where I can disable just the table preview feature and keep everything else?

**Comment by SeptemberHX** [comment]
Plugin Settings -> Render markdown table to editable table in markdown editor

**Comment by Pyroseza** [comment]
Thanks, I’ve disabled it now
