### ISSUE TITLE
Parse error in Mermaid sequence diagrams

### ISSUE THREAD

**Issue by Pyroseza** [SeptemberHX/joplin-plugin-enhancement#51]
It seems like this plugin is unable to parse _newer_ keywords for Mermaid sequence diagrams, here's an example: 

```
Could not render Graph:

Parse error on line 2:
... Purple Alice & John participant A
-----------------------^
Expecting 'SOLID_OPEN_ARROW', 'DOTTED_OPEN_ARROW', 'SOLID_ARROW', 'DOTTED_ARROW', 'SOLID_CROSS', 'DOTTED_CROSS', 'SOLID_POINT', 'DOTTED_POINT', got 'NEWLINE'
```
and as a screenshot:

![image](https://github.com/SeptemberHX/joplin-plugin-enhancement/assets/8463626/a5d6ce11-de4c-47d5-bb4e-b7adb9af8c9f)

and now here's the sample diagram text to replicate with:

```
    sequenceDiagram
    box Purple Alice & John
    participant A
    participant J
    end
    box Another Group
    participant B
    participant C
    end
    A->>J: Hello John, how are you?
    J->>A: Great!
    A->>B: Hello Bob, how is Charly?
    B->>C: Hello Charly, how are you?
```

and as you can see in Github it is correct and renders fine:

```mermaid
    sequenceDiagram
    box Purple Alice & John
    participant A
    participant J
    end
    box Another Group
    participant B
    participant C
    end
    A->>J: Hello John, how are you?
    J->>A: Great!
    A->>B: Hello Bob, how is Charly?
    B->>C: Hello Charly, how are you?
```

This example comes directly from the Mermaid docs: https://mermaid.js.org/syntax/sequenceDiagram.html

Upon closer inspection several of the reserved keywords are not able to parse, perhaps it would be best to do a run through all the updated documentation and check all newer keywords.

**Comment by Pyroseza** [comment]
Upon closer inspection several of the keywords are not able to parse, perhaps it would be best to do a run through all the updated documentation?

**Comment by SeptemberHX** [comment]
Were these keywords added in versions after 8.14.0? The plugin uses version 8.14.0 of mermaid. Maybe this issue can be fixed by upgrading mermaid library to the latest one.

**Comment by Pyroseza** [comment]
Box keyword was added in [v9.4.0](https://github.com/mermaid-js/mermaid/releases/tag/v9.4.0)

"Critical Region", "Option" and "Break" blocks were added in [v9.1.2](https://github.com/mermaid-js/mermaid/releases/tag/9.1.2)
