### ISSUE TITLE
[Feature Request] Add support of image rotate

### ISSUE THREAD

**Issue by Rhilip** [SeptemberHX/joplin-plugin-enhancement#7]
Can you add support of image rotate, for example a `{rotate=90deg}` token like will be render as `style="transform: rotate(90deg);"`

**Comment by SeptemberHX** [comment]
这个属性倒是好加上去，但是加上去之后高度还是旋转前的高度，导致图片超高了。

我不是很熟悉 css，不知道纯 css 能不能做到旋转后的高度自适应；如果要用 js 动态调整的话，那不太适合作为渲染器的一部分了

**Comment by Rhilip** [comment]
确实如此，我这边也检索了下相关资料，纯css做不到 `旋转后的高度自适应`
