### ISSUE TITLE
[BUG] Text selection not visible

### ISSUE THREAD

**Issue by Zeratoxx** [SeptemberHX/joplin-plugin-enhancement#8]
By leftclick-dragging across text you can select this text.  

### Expected:
The selection is normally indicated with a blue marker.  
Example (Enhancement plugin disabled):  
![grafik](https://user-images.githubusercontent.com/35294329/185390949-fe6937f7-9385-4282-82c1-4504230a891e.png)

### Current behavior:
In Version 1.0.0, there is no marker indication which is confusing.  
Example (Line 4 to 7 is marked but not indicated):  
![grafik](https://user-images.githubusercontent.com/35294329/185390653-bc31b58d-5c0c-4783-8922-daf565f9fd31.png)

**Comment by SeptemberHX** [comment]
Could you open dev tools `Tools -> toggle dev tools` and select the element (selected text in the editor) to get its css style properties ?

You can follow the instruction at: https://developer.chrome.com/docs/devtools/dom/

**Comment by Zeratoxx** [comment]
Thanks!
Also turns out, I didn't install the Plugin Rich Markdown

**Comment by SeptemberHX** [comment]
It should be fixed by the new release v1.1.0
